name: Rails & React Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.5.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.7

      - name: Install PostgreSQL 12 client
        run: |
          sudo apt-get -yqq install libpq-dev
    
      - name: Build and test with Rake
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          gem install bundler -v 1.17.3
          bundle install --jobs 4 --retry 3
          bin/rails db:setup
          bundle exec rake test

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm test
