name: Rails & React Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Do NOT change the version away from pg 11.5
    # > 11 and 12 both has docker container issues
    # > on Github Actions where healthcheck will die
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.5.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.7

      - name: Install PostgreSQL 11.5 client
        run: |
          sudo apt-get -yqq install libpq-dev
    
      - name: Build and test with Rake
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/rails db:setup
          bundle exec rake test

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run test:ci
